[tools]
node = "lts"
"npm:nx" = "latest"
"pipx:commitizen" = "latest"
pnpm = "latest"
pre-commit = "latest"

[shell_alias]
"syllables" = "node ./apps/syllables-cli/dist/main.js"
"syllable-map" = "node ./apps/syllable-map-cli/dist/main.js"
"synthetic-language" = "node ./apps/synthetic-language-cli/dist/main.js"
